spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/custompcbuilder}
    username: ${SPRING_DATASOURCE_USERNAME:custompcuser}
    password: ${SPRING_DATASOURCE_PASSWORD:custompcpass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:VerySecretKeyChangeMeToEnvVariable}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}